# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yasangcodes87
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: boto3test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Boto3Test

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/usersS3Database

functions:
  hello:
    handler: src/hello.handler
    environment:
      USERS_TABLE: usersS3Database
    events:
      - httpApi:
          path: /
          method: get
