# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yasangcodes87
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: boto3test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Boto3Test

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
